name: colorquizapp
description: "color quiz app for women."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  mailer: ^6.1.2
  flutter_dotenv: ^5.0.2
  url_launcher: ^6.1.5 
  flutter_pdfview: ^1.2.7
  path_provider: ^2.1.4
  logger: ^1.4.0
  flutter_native_splash: ^2.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  rename: ^2.0.1


flutter:

  uses-material-design: true

  assets:
    - assets/images/eyes/
    - assets/images/
    - assets/images/icons/
    - assets/images/hair/  
    - .env
    - assets/pdf/downloadfile.pdf

  fonts:
    - family: Metrophobic
      fonts:
        - asset: assets/fonts/Metrophobic.ttf

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  branding_bottom_padding: 24
  color_dark: "#121212"
  image_dark:  assets/images/logo.png

  android_12:
    image:  assets/images/logo.png
    icon_background_color: "#ffffff"
    image_dark:  assets/images/logo.png
    icon_background_color_dark: "#121212"

  web: false